### ISSUE TITLE
The gradio demo script will be released？

### ISSUE THREAD

**Issue by HonglinChu** [LinghaoChan/OpenTMA#4]
Hi，i try the https://swanhub.co/demo/Evan/OpenTMR. The gradio demo script will be released? I am referring the format of
https://github.com/Mathux/TMR/blob/master/app.py. But if you open source the code, it will help me save a lot of development time.

**Comment by HonglinChu** [comment]
Oh, i find the demo code https://github.com/LinghaoChan/OpenTMA-demo

**Comment by LinghaoChan** [comment]
exactly
